# Generated by Django 4.2.6 on 2023-11-02 08:08

from django.db import migrations, models
import magoso.models


class Migration(migrations.Migration):

    dependencies = [
        ('magoso', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=magoso.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
